[settings]

trusted_config_paths = [
    '~/sources',
    '/sources',
]

[tools]
node = "latest"
python = "latest"
uv = "latest"
bun = "latest"
rust = "latest"
jq = "latest"
fzf = "latest"
eza = "latest"
fd = "latest"
bat = "latest"
neovim = "latest"
shellcheck = "latest"
ripgrep = "latest"
starship = "latest"

