set -g mouse on
set-window-option -g mode-keys vi
set -g extended-keys on

bind  c  new-window      -c "#{pane_current_path}"
bind  %  split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
